version: '3'
services:

  # Service for the AllegroGraph
  allegro:
    image: bfrgoncalves/innuendo_docker_allegro:1.0.0
    restart: on-failure
    expose:
      - "10035"
    command: ["init_all"]

  # Service for the redis queue
  redis:
    image: redis
    expose:
      - "6379"

  # Service for the INNUENDO frontend. Requires the config files for the
  # application and mapping of the fastq files
  # bfrgoncalves/innuendo_docker_frontend:1.0.0
  frontend:
    image: kapsakcj/innuendo_docker_frontend:1.0.0
    privileged: true
    restart: on-failure
    volumes:
      - ./configs/app/config_frontend.py:/Frontend/INNUENDO_REST_API/config.py
      - user_data:/INNUENDO
      - ./inputs/fastq:/INNUENDO/ftp/files
      - ./inputs/backups:/INNUENDO/backups
      - ./inputs/v1/classifications:/INNUENDO/inputs/v1/classifications
      - ./inputs/v1/core_lists:/INNUENDO/inputs/v1/core_lists
      - ./inputs/v1/indexes:/INNUENDO/inputs/v1/indexes
      - ./inputs/v1/legacy_metadata:/INNUENDO/inputs/v1/legacy_metadata
      - ./inputs/v1/legacy_profiles:/INNUENDO/inputs/v1/legacy_profiles
      - ./components/Frontend/build_allegro.py:/Frontend/INNUENDO_REST_API/build_allegro.py
      - singularity_cache:/mnt/singularity_cache
      - /home/curtis/github-repos/INNUENDO_REST_API/app:/Frontend/INNUENDO_REST_API/app
    ports:
      - "5000:5000"
    depends_on:
      - "allegro"
      - "db_innuendo"
      - "db_mlst"
      - "web"
    command: ["init_allegro", "build_db", "init_app"]

  # DB for the INNUENDO application.
  db_innuendo:
    image: bfrgoncalves/innuendo_docker_db_innuendo:1.0.0
    restart: always
    environment:
      POSTGRES_USER: "innuendo"
      POSTGRES_PASSWORD: "innuendo_database"
      POSTGRES_DB: "innuendo"
    volumes:
      - ./configs/dbs/alembic_drop.sql:/docker-entrypoint-initdb.d/1-schema.sql

  # DB for the INNUENDO application.
  db_flowcraft:
    image: bfrgoncalves/innuendo_docker_db_flowcraft:1.0.0
    restart: always
    volumes:
      - ./configs/flowcraft/config_flowcraft.py:/FlowCraft_inspect/flowcraft-webapp/flowcraft-webapp/flowcraftapp/settings.py
    environment:
      POSTGRES_USER: "assemblerflow"
      POSTGRES_PASSWORD: "assflow"
      POSTGRES_DB: "assemblerflow"

  # DB for the INNUENDO wgMLST profiles.
  db_mlst:
    image: bfrgoncalves/innuendo_docker_db_mlst:1.0.0
    restart: always
    environment:
      POSTGRES_USER: "innuendo"
      POSTGRES_PASSWORD: "innuendo_database"
      POSTGRES_DB: "mlst_database"
    volumes:
      - ./configs/dbs/alembic_drop.sql:/docker-entrypoint-initdb.d/1-schema.sql

  # DB for PHYLOViZ Online.
  db_phyloviz:
    image: bfrgoncalves/innuendo_docker_db_phyloviz:1.0.0
    restart: always
    environment:
      POSTGRES_USER: "phyloviz"
      POSTGRES_PASSWORD: "phyloviz"
      POSTGRES_DB: "phyloviz"
    volumes:
      - ./configs/dbs/init.sql:/docker-entrypoint-initdb.d/1-schema.sql

  # Service for PHYLOViZ Online application
  # bfrgoncalves/phylovizonline_docker:1.0.0
  phyloviz:
    image: bfrgoncalves/phylovizonline_docker:1.0.0
    restart: on-failure
    volumes:
      - ./configs/app/phyloviz_config.js:/PHYLOVIZ/Online-PhyloViZ/config.js
    expose:
      - "80"
    depends_on:
      - "db_phyloviz"
      - "redis"
      - "web"
    command: ["init_all"]

  # Service for FlowCraft web application. Used for the inspect and report
  # system
  flowcraft:
    image: bfrgoncalves/innuendo_docker_flowcraft:1.0.0
    restart: on-failure
    expose:
      - "8000"
    volumes:
      - ./configs/flowcraft/config_flowcraft.py:/FlowCraft_inspect/flowcraft-webapp/flowcraft-webapp/flowcraftapp/settings.py
      - ./configs/flowcraft/config.json:/FlowCraft_inspect/flowcraft-webapp/flowcraft-webapp/frontend/config.json
    depends_on:
      - "db_flowcraft"
      - "web"
    command: ["init_all"]

  # Service for the INNUENDO frontend. Requires the config files for the
  # application and mapping of the fastq files. It also requires the slurm
  # conf files.
  controller:
    image: kapsakcj/innuendo_docker_controller:1.0.0
    command: ["slurmctld", "get_schemas"]
    container_name: slurmctld
    hostname: slurmctld
    privileged: true
    tty: true
    #restart: on-failure
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - ./components/Controller/slurm.conf:/etc/slurm/slurm.conf
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./configs/app/config_process.py:/Controller/INNUENDO_PROCESS_CONTROLLER/config.py
      - ./configs/nextflow/nextflow.config:/Controller/flowcraft/flowcraft/nextflow.config
      - user_data:/INNUENDO
      - ./inputs/fastq:/INNUENDO/ftp/files
      - ./inputs/v1/schemas:/INNUENDO/inputs/v1/schemas
      - ./inputs/prodigal_training_files:/INNUENDO/inputs/prodigal_training_files
      - ./inputs/v1/core_lists:/INNUENDO/inputs/v1/core_lists
      - ./inputs/serotyping_files:/INNUENDO/inputs/serotyping_files
      - singularity_cache:/mnt/singularity_cache
    expose:
      - "6817"
      - "5001"
    depends_on:
      - "slurmdbd"
      - "allegro"
      - "frontend"
      - "web"


  # service with mysql database for slurm accounting
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    privileged: true
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  # service for the the SLURM dbd.
  slurmdbd:
    image: bfrgoncalves/innuendo_docker_controller:1.0.0
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - ./components/Controller/slurm.conf:/etc/slurm/slurm.conf
      - var_log_slurm:/var/log/slurm
      - singularity_cache:/mnt/singularity_cache
    expose:
      - "6819"
    depends_on:
      - "mysql"

  # service for slurm computing node 1
  c1:
    image: bfrgoncalves/innuendo_docker_controller:1.0.0
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - ./components/Controller/slurm.conf:/etc/slurm/slurm.conf
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - singularity_cache:/mnt/singularity_cache
      - user_data:/INNUENDO
      - ./inputs/fastq:/INNUENDO/ftp/files
      - ./inputs/v1/schemas:/INNUENDO/inputs/v1/schemas
      - ./inputs/prodigal_training_files:/INNUENDO/inputs/prodigal_training_files
      - ./inputs/v1/core_lists:/INNUENDO/inputs/v1/core_lists
      - ./inputs/serotyping_files:/INNUENDO/inputs/serotyping_files
    expose:
      - "6818"
    depends_on:
      - "controller"

  # service for slurm computing node 2
  c2:
    image: bfrgoncalves/innuendo_docker_controller:1.0.0
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - ./components/Controller/slurm.conf:/etc/slurm/slurm.conf
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - singularity_cache:/mnt/singularity_cache
      - user_data:/INNUENDO
      - ./inputs/fastq:/INNUENDO/ftp/files
      - ./inputs/v1/schemas:/INNUENDO/inputs/v1/schemas
      - ./inputs/prodigal_training_files:/INNUENDO/inputs/prodigal_training_files
      - ./inputs/v1/core_lists:/INNUENDO/inputs/v1/core_lists
      - ./inputs/serotyping_files:/INNUENDO/inputs/serotyping_files
    expose:
      - "6818"
    depends_on:
      - "controller"

  # Service for the nginx web server. it requires mapping of the nginx conf
  # to be able to access all the other processes from the browser.
  web:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./configs/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - static-content:/usr/src/app
      - ./configs/app/config_reports.js:/usr/src/app/config.js
      - flowcraft-content:/usr/src/flowcraft
    ports:
      - "80:80"
      - "82:82"
      - "10035:10035"


volumes:
  static-content:
  flowcraft-content:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  singularity_cache:
  user_data:

